<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>WinExe</OutputType>
        <TargetFramework>net8.0-windows</TargetFramework>
        <Nullable>enable</Nullable>
        <UseWindowsForms>true</UseWindowsForms>
        <ImplicitUsings>enable</ImplicitUsings>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="Vortice.Direct3D12" Version="3.6.2" />
      <PackageReference Include="Vortice.DXGI" Version="3.6.2" />
      <PackageReference Include="Vortice.Mathematics" Version="1.9.3" />
      <PackageReference Include="Vortice.Win32" Version="2.2.7" />
    </ItemGroup>

</Project>